apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webdemo
  name: webdemo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: webdemo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webdemo
    spec:
      containers:
      - image: ymian/webdemo
        imagePullPolicy: Always
        name: webdemo
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: 
          limits:
            cpu: 1
          requests:
            cpu: 1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webdemo
  name: webdemo
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webdemo